name: Auto Commit and Push

on:
  push:
    branches:
      - main  # Runs whenever the main branch is updated
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto commit from GitHub Actions" || exit 0
          git push origin main
